# Generated by Django 4.2.4 on 2023-08-01 19:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Image",
            new_name="SiteImage",
        ),
    ]
